import type { Metadata } from "next";
import { PageShell, RepoTabs, StatusBadge } from "../../../../components/SiteShell";
import { alphaRelease, repositoryIdentity } from "../../../../data/collaboration";

export const metadata: Metadata = { title: `${alphaRelease.tag} · Schema Preview · Jurissemble`, description: alphaRelease.title, openGraph: { images: [] }, twitter: { images: [] } };

export default function ReleasePage() {
  return <PageShell><section className="release-hero"><div><p className="breadcrumb"><a href={repositoryIdentity.path}>jiaozhu7 / construction-legal-engineering</a> / releases / {alphaRelease.tag}</p><p className="section-kicker">{alphaRelease.kind} · ALPHA</p><h1>{alphaRelease.tag}</h1><h2>{alphaRelease.title}</h2><p>这是不可变的结构预览快照，用于检查对象、提案、评审和依赖页面能否闭环；它不是经过专业核验的法律内容Release。</p></div><div className="release-stamp preview-stamp"><span>SCHEMA</span><strong>28</strong><small>AUG · 2026</small><b>Maintainer · {alphaRelease.maintainer}</b></div></section><RepoTabs active="releases" />
    <section className="repo-content"><div className="release-gate-banner"><StatusBadge tone="amber">NOT A LEGAL CONTENT RELEASE</StatusBadge><strong>来源、权利、专业含义与实践复核均未达到发布门槛。</strong></div><div className="release-layout"><main><section className="object-section"><div className="object-section-head"><span>01</span><div><small>IMMUTABLE SAMPLE MANIFEST</small><h2>锁定的结构示例</h2></div></div><div className="release-module"><StatusBadge tone="amber">MODULE · PREVIEW</StatusBadge><div><code>{alphaRelease.module.id}</code><strong>{alphaRelease.module.version}</strong></div></div><div className="dependency-list">{alphaRelease.objects.map((item) => <a href={item.objectId.includes("PROPOSITION") ? `${repositoryIdentity.path}/objects/${item.objectId}` : "#limitations"} key={item.objectId}><div><code>{item.objectId}</code><h3>{item.label}</h3></div><strong>{item.revisionId}</strong></a>)}</div></section><section className="object-section"><div className="object-section-head"><span>02</span><div><small>SCHEMA CHANGELOG</small><h2>本次预览验证什么</h2></div></div><ol className="release-list">{alphaRelease.changes.map((item) => <li key={item}>{item}</li>)}</ol></section><section className="object-section"><div className="object-section-head"><span>03</span><div><small>CONTENT RELEASE GATES</small><h2>成为法律内容Release还缺什么</h2></div></div><div className="launch-checklist">{["SourceAnchor达到VERIFIED","legal_meaning与source复核完成","rights复核确认公开许可","结构测试通过且无阻断冲突","维护者冻结不可变Manifest"].map((item) => <div key={item}><span>○</span>{item}</div>)}</div></section></main><aside className="release-sidebar" id="limitations"><h2>Known limitations</h2><ul>{alphaRelease.limitations.map((item) => <li key={item}>{item}</li>)}</ul><h2>Canonical reference</h2><pre>{alphaRelease.canonicalReference}</pre><div className="prototype-action">任何项目引用本预览都必须继续显示其Schema Preview性质，不得升级描述为已发布法律结论。</div><a className="button primary full-button" href="/projects/qianhai-notice-playbook">查看Project Manifest <span>→</span></a></aside></div></section>
  </PageShell>;
}
