import type { Metadata } from "next";
import { PageShell, RepoTabs, StatusBadge } from "../../components/SiteShell";
import { legalTests, mappings, repoStats, repository } from "../../data/registry";
import { alphaRelease, noticeModule, proposal, propositionObject, repositoryIdentity } from "../../data/collaboration";

export const metadata: Metadata = { title: "建设工程法律工程 · jiaozhu7 · Jurissemble", description: repositoryIdentity.description, openGraph: { images: [] }, twitter: { images: [] } };

export default function RepositoryPage() {
  return <PageShell><section className="repo-header"><div className="repo-title-row"><span className="repo-glyph large">CLE</span><div><p><a href="/jiaozhu7">{repository.owner}</a> / <strong>{repository.name}</strong></p><h1>{repository.title}</h1></div><div className="badge-row"><StatusBadge>PUBLIC</StatusBadge><StatusBadge tone="amber">SCHEMA PREVIEW</StatusBadge></div></div><p className="repo-description">由jiaozhu7维护的首个公开法律仓库：围绕工程通知与变更，组织来源、法律问题、工作模块、提案和版本。</p><div className="repo-meta"><span>Owner · jiaozhu7</span><span>Maintainer · jiaozhu7</span><span>◉ {repository.version}</span><span>更新于 {repositoryIdentity.updatedAt}</span><span>{repositoryIdentity.license}</span></div><div className="scope-banner"><strong>仓库边界</strong><span>建设工程是一个账号的首个仓库，不是平台内容边界。当前内容仍为结构预览：没有已核验来源、完成的专业复核或法律内容Release。</span></div></section><RepoTabs active="overview" />
    <section className="repo-layout"><div className="repo-readme"><div className="file-heading"><span>README.md</span><b>Public repository · maintained by jiaozhu7</b></div><div className="readme-body"><p className="section-kicker">REPOSITORY OVERVIEW</p><h2>把建设工程通知与变更维护成一个可协作项目</h2><p>仓库尝试把分散在合同、项目事件、法律研究和实践流程中的内容放进同一版本脉络。当前样本只证明页面、对象和协作结构，尚不提供可直接用于真实项目的法律结论。</p><div className="readme-callout"><strong>如何浏览这个仓库</strong><p>先从Module理解工作流程，再查看Object、Source、Proposal和Test；任何复用都应锁定精确revision并重新核验法域、合同版本、事实和截止时点。</p></div><h3>可以怎样贡献</h3><ul><li>补充一条公开来源的版本、精确位置和权利状态</li><li>指出现有命题的例外、反例或适用范围问题</li><li>对通知或变更模块提交有理由的修改提案</li><li>按法律含义、来源、结构、权利或实践范围完成Review</li></ul><div className="repo-showcase-grid"><a href={`${repositoryIdentity.path}/modules/notice`}><StatusBadge tone="amber">MODULE · PROTOTYPE</StatusBadge><h3>{noticeModule.title}</h3><p>{noticeModule.purpose}</p><code>{noticeModule.version}</code></a><a href={`${repositoryIdentity.path}/objects/${propositionObject.objectId}`}><StatusBadge tone="amber">OBJECT · {propositionObject.sourceStatus}</StatusBadge><h3>{propositionObject.title}</h3><p>{propositionObject.summary}</p><code>{propositionObject.revisionId}</code></a><a href={`${repositoryIdentity.path}/proposals/${proposal.id}`}><StatusBadge tone="amber">PROPOSAL · EXAMPLE</StatusBadge><h3>{proposal.id} · {proposal.title}</h3><p>{proposal.reason}</p><code>{proposal.baseRevision} → {proposal.proposedRevision}</code></a><a href={`${repositoryIdentity.path}/releases/${alphaRelease.tag}`}><StatusBadge tone="amber">SCHEMA PREVIEW</StatusBadge><h3>{alphaRelease.tag}</h3><p>{alphaRelease.title}</p><code>6 example revisions locked</code></a></div><p><a className="text-link" href={`${repositoryIdentity.path}/research`}>查看本仓库的研究与未决问题 →</a></p></div></div>
      <aside className="repo-sidebar"><h3>Repository status</h3><div className="repo-health"><span className="status-dot amber-dot" /><strong>Public · schema preview</strong></div><div className="health-list"><p><b>内容阶段</b><span>SCHEMA_EXAMPLE</span></p><p><b>来源</b><span>0 VERIFIED</span></p><p><b>专业复核</b><span>0 completed</span></p><p><b>许可</b><span>PENDING</span></p><p><b>可直接实务使用</b><span>NO</span></p></div><div className="sidebar-stats"><div><b>{repoStats.sources}</b><span>Source leads</span></div><div><b>6</b><span>Example units</span></div><div><b>1</b><span>Proposal example</span></div><div><b>0</b><span>Content releases</span></div></div><h3>下一步可贡献</h3><a className="sidebar-link" href={`${repositoryIdentity.path}/research`}><span>补齐来源锚点</span><small>version · pinpoint · rights →</small></a><a className="sidebar-link" href={`${repositoryIdentity.path}/proposals/${proposal.id}`}><span>检查语义Diff</span><small>scope · source · effect →</small></a><a className="sidebar-link" href="/docs"><span>查看贡献规则</span><small>fork · propose · review →</small></a><h3>结构测试</h3><p>{mappings.length}条候选映射 · {legalTests.length}项测试</p></aside>
    </section>
  </PageShell>;
}
