import type { Metadata } from "next";
import { PageShell, RepoTabs, StatusBadge } from "../../../../components/SiteShell";
import { legalDisclaimer, propositionObject, repositoryIdentity } from "../../../../data/collaboration";

export const metadata: Metadata = { title: `${propositionObject.title} · LegalUnit · Jurissemble`, description: propositionObject.summary, openGraph: { images: [] }, twitter: { images: [] } };

export default function LegalUnitPage() {
  return <PageShell><section className="object-hero"><p className="breadcrumb"><a href={repositoryIdentity.path}>jiaozhu7 / construction-legal-engineering</a> / units / proposition</p><div className="object-titlebar"><div><p className="section-kicker">LEGALUNIT · PROPOSITION</p><h1>{propositionObject.title}</h1></div><div className="badge-row"><StatusBadge tone="amber">{propositionObject.contentStage}</StatusBadge><StatusBadge tone="amber">SOURCE · {propositionObject.sourceStatus}</StatusBadge><StatusBadge>{propositionObject.maintenanceStatus}</StatusBadge></div></div><p className="object-summary">{propositionObject.summary}</p><div className="unit-answer-grid"><article><small>解决什么</small><strong>{propositionObject.purpose}</strong></article><article><small>何时可能适用</small><strong>履约阶段；法域、合同版本和截至时点必须另行核验</strong></article><article><small>何时不能直接使用</small><strong>缺少适用合同原文、精确条款位置或具体事件事实时</strong></article><article><small>当前可信状态</small><strong>结构示例 · 来源缺失 · 未复核 · 未经实践使用</strong></article></div><div className="legal-warning"><strong>{legalDisclaimer}</strong><span>真实复用前必须核验合同、法域、事实、时点和来源权利。</span></div></section><RepoTabs active="objects" />
    <section className="object-layout"><main className="object-main">
      <section className="object-section"><div className="object-section-head"><span>01</span><div><small>IDENTITY</small><h2>身份</h2></div></div><dl className="metadata-grid"><div><dt>unit_id</dt><dd><code>{propositionObject.objectId}</code></dd></div><div><dt>revision_id</dt><dd><code>{propositionObject.revisionId}</code></dd></div><div><dt>unit_type</dt><dd>{propositionObject.objectType}</dd></div><div><dt>knowledge_kind</dt><dd>{propositionObject.knowledgeKind}</dd></div></dl></section>
      <section className="object-section"><div className="object-section-head"><span>02</span><div><small>APPLICABILITY</small><h2>适用性</h2></div></div><div className="scope-grid">{Object.entries(propositionObject.scope).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div></section>
      <section className="object-section"><div className="object-section-head"><span>03</span><div><small>INTERFACE</small><h2>输入与输出</h2></div></div><div className="content-record">{Object.entries(propositionObject.interface).map(([key, value]) => <div key={key}><span>{key}</span><p>{value}</p></div>)}</div></section>
      <section className="object-section"><div className="object-section-head"><span>04</span><div><small>SUBSTANCE</small><h2>实质内容</h2></div></div><div className="content-record">{Object.entries(propositionObject.content).map(([key, value]) => <div key={key}><span>{key}</span><p>{value}</p></div>)}</div></section>
      <section className="object-section source-section"><div className="object-section-head"><span>05</span><div><small>PROVENANCE</small><h2>来源链</h2></div></div><div className="source-record"><div><StatusBadge tone="amber">{propositionObject.source.status}</StatusBadge><code>{propositionObject.source.id}</code></div><h3>{propositionObject.source.title}</h3><p>{propositionObject.source.pinpoint}</p><dl><div><dt>authority_type</dt><dd>{propositionObject.source.authority}</dd></div><div><dt>rights</dt><dd>{propositionObject.source.copyright}</dd></div></dl></div><div className="caution-box"><b>来源尚未核验</b><p>SourceAnchor是独立来源层。本占位记录不能支持实体法律结论，也不得公开复制受保护合同全文。</p></div></section>
      <section className="object-section"><div className="object-section-head"><span>06</span><div><small>CONTESTABILITY</small><h2>分歧与未知</h2></div></div><div className="content-record">{Object.entries(propositionObject.contestability).map(([key, value]) => <div key={key}><span>{key}</span><p>{value}</p></div>)}</div></section>
      <section className="object-section"><div className="object-section-head"><span>07</span><div><small>DEPENDENCIES</small><h2>类型化关系</h2></div></div><div className="relation-list">{propositionObject.relations.map(([type, target, reason]) => <div key={type}><code>{type}</code><strong>{target}</strong><p>{reason}</p></div>)}</div></section>
      <section className="object-section"><div className="object-section-head"><span>08</span><div><small>GOVERNANCE</small><h2>治理与待复核范围</h2></div></div><dl className="metadata-grid"><div><dt>owner</dt><dd>{propositionObject.owner}</dd></div><div><dt>access</dt><dd>{propositionObject.governance.access}</dd></div><div><dt>license</dt><dd>{propositionObject.governance.license}</dd></div><div><dt>machine_origin</dt><dd>{propositionObject.machineOrigin}</dd></div></dl><div className="review-list">{propositionObject.requiredReviews.map((review) => <article key={review.scope}><div><StatusBadge tone="amber">{review.status}</StatusBadge><code>{review.scope}</code></div><h3>待完成复核</h3><p>{review.requirement}</p></article>)}</div></section>
      <section className="object-section"><div className="object-section-head"><span>09</span><div><small>VALIDATION</small><h2>验证与维护</h2></div></div><div className="state-dimension-grid"><article><h3>practice_status</h3><code>{propositionObject.practiceStatus}</code></article><article><h3>maintenance_status</h3><code>{propositionObject.maintenanceStatus}</code></article><article><h3>source_status</h3><code>{propositionObject.sourceStatus}</code></article></div><div className="validation-panels"><article><h3>Assumptions</h3><ul>{propositionObject.assumptions.map((item) => <li key={item}>{item}</li>)}</ul></article><article><h3>Taxonomy gaps</h3><ul>{propositionObject.taxonomyGaps.map((item) => <li key={item}>{item}</li>)}</ul></article><article><h3>Tests</h3><ul>{propositionObject.tests.map((item) => <li key={item}><code>{item}</code></li>)}</ul></article></div></section>
    </main><aside className="object-sidebar"><h2>可以做什么</h2><a href="/projects/qianhai-notice-playbook"><small>REUSE</small><strong>引用到项目蓝图</strong><span>lock revision →</span></a><a href={`${repositoryIdentity.path}/proposals/CP-001`}><small>PROPOSE</small><strong>提出修改</strong><span>semantic diff →</span></a><a href={`${repositoryIdentity.path}/research`}><small>SOURCE</small><strong>补充来源</strong><span>pinpoint & rights →</span></a><h2>Canonical reference</h2><pre>{propositionObject.canonicalReference}</pre><p className="prototype-action">当前引用仅用于原型演示。由于来源和复核门槛未完成，它不能作为生产法律依赖。</p><h2>Export alias</h2><pre>{propositionObject.exportAlias}</pre></aside></section>
  </PageShell>;
}
