import type { Metadata } from "next";
import Link from "next/link";
import { PageShell, StatusBadge } from "../components/SiteShell";
import { foundingRepository } from "../data/product";
import { founder } from "../data/collaboration";

export const metadata: Metadata = { title: "jiaozhu7 · 贡献者 · Jurissemble · 律构集", description: "创始贡献者jiaozhu7及其首个公开法律仓库。" };

export default function ContributorProfilePage() {
  return <PageShell><section className="profile-hero"><div className="profile-avatar">J7</div><div><p className="eyebrow"><span /> FOUNDING CONTRIBUTOR</p><h1>{founder.username}</h1><p>{founder.bio} 当前主页只展示可以从网站、仓库和版本记录复核的贡献，不代表律师资质认证、专业排名或未经验证的影响力。</p></div><StatusBadge tone="green">CONTRIBUTOR PROFILE</StatusBadge></section><section className="content-section compact profile-layout"><div><div className="section-head"><div><p className="section-kicker">REPOSITORIES</p><h2>公开仓库</h2></div><p>当前只有一个真实示范仓库，不制造Star、Fork、合并、用户或内容发布记录。</p></div><Link className="featured-repo-card" href={foundingRepository.path}><div className="repo-card-top"><span className="repo-glyph">CLE</span><div><p>{foundingRepository.owner} / <strong>{foundingRepository.slug}</strong></p><h3>{foundingRepository.title}</h3></div><StatusBadge tone="amber">{foundingRepository.stage}</StatusBadge></div><p>{foundingRepository.description}</p><div className="catalog-tags">{foundingRepository.jurisdictions.concat(foundingRepository.topics).map((tag) => <span key={tag}>{tag}</span>)}</div><div className="mini-stats">{foundingRepository.facts.map(([value, label]) => <span key={label}><b>{value}</b> {label}</span>)}</div></Link><section className="profile-contribution-section"><div className="section-head"><div><p className="section-kicker">VERIFIABLE CONTRIBUTION</p><h2>项目贡献范围</h2></div><p>署名跟随具体构件和版本；以下内容可在项目档案与公开代码中交叉检查。</p></div><div className="profile-contribution-grid">{[["RESEARCH", "研究问题与FLC+D架构"], ["PRODUCT", "Legal Module对象与社区协作模型"], ["SPEC", "Schema、信任状态与治理边界"], ["PROTOTYPE", "网站原型、本地工具与验证路线"]].map(([code, title]) => <article key={code}><code>{code}</code><h3>{title}</h3></article>)}</div><div className="section-link-row"><Link className="button secondary" href="/dossier">查看完整项目档案 <span>→</span></Link><a className="button secondary" href="https://github.com/dreamlee666/jurissemble" target="_blank" rel="noreferrer">查看GitHub ↗</a></div></section></div><aside className="profile-sidebar"><h2>贡献者概览</h2><p>以建设工程仓库验证法律工作能否像项目一样被维护。账号不是网站主题边界。</p><dl><div><dt>公开仓库</dt><dd>1</dd></div><div><dt>维护仓库</dt><dd>1</dd></div><div><dt>已合并提案</dt><dd>0</dd></div><div><dt>法律内容Release</dt><dd>0</dd></div></dl><h2 className="sidebar-subtitle">当前真实性边界</h2><ul className="activity-list"><li>已有可运行产品原型</li><li>已有结构化模块样本</li><li>已有公开研究计划</li><li>尚无实证有效性结论</li></ul><Link className="sidebar-link" href="/dossier"><span>项目证据与边界</span><small>project dossier →</small></Link></aside></section></PageShell>;
}
